---
- name: Create Podman containers
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create container
      containers.podman.podman_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        state: started
        command: sleep infinity
      loop: "{{ molecule_yml.platforms }}"

