---
- name: Destroy molecule containers
  hosts: all
  gather_facts: false
  tasks:
    - name: Remove Podman container
      delegate_to: localhost
      containers.podman.podman_container:
        name: "{{ inventory_hostname }}"
        state: absent

