---
dependency:
  name: galaxy

driver:
  name: podman

platforms:
  - name: molecule-debian
    image: molecule-debian-python:latest
  - name: molecule-ubuntu
    image: molecule-ubuntu-python:latest
  - name: molecule-fedora
    image: molecule-fedora-python:latest
  - name: molecule-archlinux
    image: molecule-arch-python:latest

provisioner:
  name: ansible
verifier:
  name: ansible

