---
rustup_prefix_path: "{{ ansible_env.HOME }}/.local/share/cargo/bin"
rustup_script_url: "https://sh.rustup.rs"
rustup_script_local_path: "/tmp/rustup-init.sh"
rustup_cargo_home: "{{ ansible_env.HOME }}/.local/share/cargo"
rustup_home: "{{ ansible_env.HOME }}/.local/share/rustup"
rustup_rust_binaries:
  - cargo
  - rustup
  - rustc
