galaxy_info:
  role_name: helix
  namespace: tools
  author: your_name_here
  description: Ansible role to install Helix editor
  license: MIT
  min_ansible_version: '2.12'
  platforms:
    - name: Debian
    - Ubuntu
    - Fedora
    - Archlinux

