---
- name: Gather only ansible_env.HOME fact
  ansible.builtin.setup:
    filter:
      - '!all'
      - 'ansible_env.HOME'

- name: Install rustup to have cargo, rustc and all toolchain for cargo install
  ansible.builtin.include_tasks: rustup_install.yaml

- name: Install Rust packages using include_tasks loop
  ansible.builtin.include_tasks: cargo_install_package.yaml
  loop: "{{ rustup_cargo_list }}"
  loop_control:
    loop_var: package
  ignore_errors: true
