---
galaxy_info:
  author: konradkon
  description: This role installs astonishing Rust tools for my usage.
  license: GPL-3.0-or-later
  min_ansible_version: '2.18'
  galaxy_tags:
    - rust
    - rustup
    - cargo
    - rustc

dependencies: []
