---
rustup_cargo_list:
  - name: alacritty
  - name: atac
  - name: bacon
  - name: bat
  - name: bottom
  - name: cargo-asm
  - name: cargo-binstall
  - name: cargo-deny
  - name: cargo-nextest
  - name: cargo-sweep
  - name: cargo-tarpaulin
  - name: code2prompt
  - name: codeberg-cli
  - name: codesnap-cli
  - name: coreutils
  - name: cyme
  - name: difftastic
  - name: dotter
  - name: dua-cli
  - name: fd-find
  - name: flamegraph
  - name: gitui
  - name: grex
  - name: httm
  - name: hyperfine
  - name: jaq
  - name: jj-cli
  - name: just
  - name: kondo
  - name: ludusavi
  - name: lychee
  - name: mdbook
  - name: mdcat
  - name: monolith
  - name: mprocs
  - name: navi
  - name: netscanner
  - name: nomino
  - name: oculante
  - name: onefetch
  - name: oxker
  - name: pastel
  - name: presenterm
  - name: rainfrog
  - name: repgrep
  - name: ripgrep
  - name: rusti-cal
  - name: rustypipe-cli
  - name: sqlx-cli
  - name: starship
  - name: tabiew
  - name: taplo-cli
  - name: tealdeer
  - name: television
  - name: termusic-server
    dependencies:
      - protobuf-compiler
      - libasound2-dev
  - name: tokei
  - name: typos-cli
  - name: typst-cli
  - name: wild-linker
  - name: xan
  - name: yazi-cli
  - name: yazi-fm
  - name: zellij
  - name: zoxide
