---
rustup_cargo_list:
  - alacritty
  - atac
  - bacon
  - bat
  - bottom
  - cargo-asm
  - cargo-binstall
  - cargo-deny
  - cargo-nextest
  - cargo-sweep
  - cargo-tarpaulin
  - code2prompt
  - codeberg-cli
  - codesnap-cli
  - coreutils
  - cyme
  - difftastic
  - dotter
  - dua-cli
  - fd-find
  - flamegraph
  - gitui
  - grex
  - httm
  - hyperfine
  - jaq
  - jj-cli
  - just
  - kondo
  - ludusavi
  - lychee
  - mdbook
  - mdcat
  - monolith
  - mprocs
  - navi
  - netscanner
  - nomino
  - oculante
  - onefetch
  - oxker
  - pastel
  - presenterm
  - rainfrog
  - repgrep
  - ripgrep
  - rusti-cal
  - rustypipe-cli
  - sqlx-cli
  - starship
  - tabiew
  - taplo-cli
  - tealdeer
  - television
  - termusic-server
  - tokei
  - typos-cli
  - typst-cli
  - wild-linker
  - xan
  - yazi-cli
  - yazi-fm
  - zellij
  - zoxide
