---
rustup_cargo_list:
  - name: alacritty
    dependencies:
      - cmake
      - g++
      - pkg-config
      - libfontconfig1-dev
      - libxcb-xfixes0-dev
      - libxkbcommon-dev
      - python3
    config:
      src: alacritty/alacritty.toml
      dest: '~/.config/alacritty/alacritty.toml'
  - name: atac
  - name: bacon
  - name: bat
  - name: bottom
  - name: cargo-asm
  - name: cargo-binstall
  - name: cargo-deny
  - name: cargo-deb
  - name: cargo-mutants
  - name: cargo-nextest
  - name: cargo-sweep
  - name: cargo-tarpaulin
  - name: code2prompt
  - name: codeberg-cli
  - name: codesnap-cli
  - name: coreutils
  - name: cyme
  - name: difftastic
    dependencies:
      - gcc
  - name: dotter
  - name: dua-cli
  - name: dysk
    dependencies:
      - build-essential
  - name: eza
  - name: fd-find
    dependencies:
      - make
  - name: flamegraph
    dependencies:
      - linux-tools-common
      - linux-tools-generic
  - name: feroxbuster
  - name: gitui
    dependencies:
      - gcc
      - openssl
      - perl
      - python3
  - name: grex
  - name: heretek
    dependencies:
      - gdb
  - name: httm
  - name: hyperfine
  - name: jnv
  - name: jaq
  - name: jj-cli
    dependencies:
      - libssl-dev
      - openssl
      - pkg-config
      - build-essential
  - name: just
  - name: kondo
  - name: ludusavi
    dependencies:
      - gcc
      - cmake
      - libx11-dev
      - libxcb-composite0-dev
      - libfreetype6-dev
      - libexpat1-dev
      - libfontconfig1-dev
      - libgtk-3-dev
  - name: lychee
    dependencies:
      - gcc
      - pkg-config
      - libc6-dev
      - libssl-dev
  - name: mdbook
  - name: monolith
  - name: mprocs
  - name: navi
  - name: netscanner
  - name: nomino # TODO
  - name: oculante
  - name: onefetch
    dependencies:
      - cmake
  - name: oxker
  - name: pastel
  - name: pay-respects
  - name: presenterm
  - name: procs
  - name: rainfrog
  - name: repgrep
  - name: resvg
  - name: ripgrep
  - name: rip2
  - name: riffdiff
  - name: rustscan
  - name: rusti-cal
  - name: rustypipe-cli
  - name: sqlx-cli
  - name: samply
  - name: skim
  - name: scooter
  - name: starship
  - name: taplo-cli
    dependencies:
      - libssl-dev
  - name: tealdeer
  - name: television
  - name: termusic-server
    dependencies:
      - protobuf-compiler
      - libasound2-dev
  - name: tokei
  - name: topgrade
    config:
      src: topgrade/topgrade.toml
      dest: ~/.config/topgrade/topgrade.toml
  - name: typos-cli
  - name: typst-cli
  - name: wild-linker
  - name: xan
  - name: xh
  - name: [yazi-cli, yazi-fm]
    dependencies:
      - jq
      - ffmpeg
      - 7zip
      - imagemagick
      - poppler-utils
      - wl-clipboard
  - name: zellij
    config:
      src: zellij/config.kdl
      dest: '~/.config/zellij/config.kdl'
  - name: zoxide
