---
- name: Ensure Homebrew is installed
  ansible.builtin.import_tasks: brew_install.yaml

- name: Install and update Homebrew packages
  ansible.builtin.import_tasks: homebrew_install_packages.yaml
